name: usg_jub
description: The web app for USG Jacobs University.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.0
  firebase_analytics: ^9.0.0-dev.4
  firebase_auth: ^3.1.3
  firebase_core: ^1.7.0
  firebase_storage: ^10.0.5
  flutter:
    sdk: flutter
  get: ^4.3.8
  image_picker: ^0.8.4+3
  json_annotation: ^4.1.0
  reactive_forms: ^10.6.2
  responsive_framework: ^0.1.4
  rounded_loading_button: ^2.0.9
  sentry_flutter: ^6.0.1
  uuid: ^3.0.5

dev_dependencies:
  build_runner: ^2.0.0
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.3.1
  json_serializable: ^6.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/2.0x/
    - assets/3.0x/

flutter_native_splash:
  color: "#eeeeee"
  color_dark: "#444444"
  image: assets/usg_logo_md.png

  android: false
  ios: false
  web: true